import mongoose from 'mongoose'

const UserSchema = new mongoose.Schema({
    username:{//用户名
        type:String,
        unique:true,//不可重复
        required:true,//必须输入
        trim:true
    },
    nickname:{//用户名
        type:String,
        unique:true,//不可重复
        trim:true
    },
    password:{//用户密码
        type:String,
        required:true,
        trim:true
    },
    avatar:String,//用户头像
    wallpaper:[{//个人中心页背景
        type:String
    }],
    description:{//用户个性签名
        type:String,
        trim:true
    },
    token:String,//用户登录凭证
    discusses:[{//记录用户发表过复数个讨论(复数个信息用[{}]包起来)
        type:mongoose.SchemaTypes.ObjectId,
        ref:'Discuss'//关联到讨论模型
    }],
    helpdiscusses:[{//记录用户发表过复数个讨论(复数个信息用[{}]包起来)
        type:mongoose.SchemaTypes.ObjectId,
        ref:'Helpdiscuss'//关联到讨论模型
    }],
    likediscusses:[{//记录用户发表过复数个讨论(复数个信息用[{}]包起来)
        type:mongoose.SchemaTypes.ObjectId,
        ref:'Likediscuss'//关联到讨论模型
    }],
    unlikediscusses:[{//记录用户发表过复数个讨论(复数个信息用[{}]包起来)
        type:mongoose.SchemaTypes.ObjectId,
        ref:'Unlikediscuss'//关联到讨论模型
    }],
    mcommodities:[{//记录用户发布过的复数个商品(卖家)
        type:mongoose.SchemaTypes.ObjectId,
        ref:'Commodity'//关联到商品模型
    }],
    bcommodities:[{//记录用户已够买过的复数个商品(买家)
        type:mongoose.SchemaTypes.ObjectId,
        ref:'Commodity'//关联到商品模型
    }],
    stores:[{
        type:mongoose.SchemaTypes.ObjectId,
        ref:'Store'//关联到商铺模型
    }],
    cinformations:[{//记录商铺发布商品相关信息
        type:mongoose.SchemaTypes.ObjectId,
        ref:'Storecommodity'//关联到商品模型
    }],
    groupbuys:[{
        type:mongoose.SchemaTypes.ObjectId,
        ref:'Groupbuy'
    }],
    secondhands:[{
        type:mongoose.SchemaTypes.ObjectId,
        ref:'Secondhand'
    }],
    collects:[{//收藏夹-->商品类
        type:mongoose.SchemaTypes.ObjectId,
        ref:'Commodity'//关联到商品模型
    }],
    collects2:[{//收藏夹-->二手类
        type:mongoose.SchemaTypes.ObjectId,
        ref:'Secondhand'//关联到商品模型
    }],
    collects3:[{//收藏夹-->团购类
        type:mongoose.SchemaTypes.ObjectId,
        ref:'Groupbuy'//关联到商品模型
    }],
    collects4:[{//收藏夹-->商铺商品
        type:mongoose.SchemaTypes.ObjectId,
        ref:'Storecommodity'//关联到商铺商品模型
    }],
    shoppingcarts:[{
        type:mongoose.SchemaTypes.ObjectId,
        ref:'Commodity'//关联到商品模型
    }],
    shoppingcarts2:[{
        type:mongoose.SchemaTypes.ObjectId,
        ref:'Secondhand'//关联到二手模型
    }],
    shoppingcarts3:[{
        type:mongoose.SchemaTypes.ObjectId,
        ref:'Groupbuy'//关联到团购模型
    }],
    likesd:[{
        type:mongoose.SchemaTypes.ObjectId,
        ref:'Discuss'//点赞
    }],
    likesh:[{
        type:mongoose.SchemaTypes.ObjectId,
        ref:'Helpdiscuss'
    }],
    likesl:[{
        type:mongoose.SchemaTypes.ObjectId,
        ref:'Likediscuss'
    }],
    likesu:[{
        type:mongoose.SchemaTypes.ObjectId,
        ref:'Unlikediscuss'
    }],
    followers:[{//关注
        type:mongoose.SchemaTypes.ObjectId,
        ref:'User'
    }],
    followers2:[{//关注
        type:mongoose.SchemaTypes.ObjectId,
        ref:'Store'
    }],
    pletters:[{//私信信息
        type:mongoose.SchemaTypes.ObjectId,
        ref:'Pletter'
    }],
    fans:[{//关注
        type:mongoose.SchemaTypes.ObjectId,
        ref:'User'
    }]
})

const User = mongoose.model('User',UserSchema)
export default User